package generator

import model.FieldMeta
import java.io.File

fun generateTypeScriptTypeFromFields(
    typeName: String,
    fields: List<FieldMeta>,
    outputDir: String
) {
    val ts = buildString {
        appendLine("/**")
        appendLine(" * Generated by Kotlin DSL Generator")
        appendLine(" * 日本語項目名は各プロパティのコメントに記載")
        appendLine(" */")
        appendLine("export interface $typeName {")
        fields.forEach { field ->
            appendLine("  /** ${field.label} */")
            appendLine("  ${field.id}: string;")
        }
        appendLine("}")
    }
    File(outputDir, "$typeName.ts").writeText(ts)
    println("Generated: $typeName.ts in $outputDir")
}
