/**
 * Generated by Kotlin DSL Generator
 * 日本語項目名は各プロパティのコメントに記載
 */
export interface DetailTableRow {
  /** 商品番号 */
  itemNo: string;
  /** 商品名 */
  itemName: string;
  /** 数量 */
  qty: string;
  /** 単価 */
  unitPrice: string;
}
