/**
 * Generated by Kotlin DSL Generator
 * 日本語項目名は各プロパティのコメントに記載
 */
export interface CustomerSearchForm {
  /** 顧客ID */
  customerId: string;
  /** 氏名 */
  name: string;
  /** 検索 */
  Search: string;
}
