/**
 * Generated by Kotlin DSL Generator
 * 日本語項目名は各プロパティのコメントに記載
 */
export interface CustomerTableRow {
  /** 顧客ID */
  customerId: string;
  /** 氏名 */
  name: string;
  /** 電話番号 */
  phone: string;
  /** メール */
  email: string;
}
